language: ruby
cache: bundler
rvm:
- 2.0.0
before_install:
  - gem update --system
  - gem update bundler
  - gem --version
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database demoshopping_test'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace